### ISSUE TITLE
ImportError: No module named displacy.server

### ISSUE THREAD

**Issue by baditaflorin** [explosion/spacy-services#2]
python displacy/app.py 
Traceback (most recent call last):
  File "displacy/app.py", line 1, in <module>
    from displacy.server import APP, get_model
ImportError: No module named displacy.server

**Comment by nishankmahore** [comment]
Change folder name displacy_service to displacy

**Comment by honnibal** [comment]
Thanks for helping here @nishankmahore --- I haven't been watching this repo properly.

I think this should be fixed with the latest pull request.
